---
name: CI
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'webapp'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible-tower-cli
      
      - name: deploy
        run: |
          tower-cli config host ${{ secrets.ANSIBLE_URL }}
          tower-cli config username ${{ secrets.ANSIBLE_USER }}
          tower-cli config password ${{ secrets.ANSIBLE_PASSWORD }}
          tower-cli job launch --job-template=10 
          
